/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Triangle.glb -T --types 
Files: .\Triangle.glb [4.03KB] > D:\VI\ring shader\ring-react\public\models\Triangle-transformed.glb [2.78KB] (31%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
  }
  materials: {
    Base_Triangle: THREE.MeshStandardMaterial
    Emission_Triangle: THREE.MeshStandardMaterial
  }
  //@ts-ignore
  animations: GLTFAction[]
}

import { useMemo } from 'react'

export function TriangleModel({ baseColor = '#ffffff', ...props }: JSX.IntrinsicElements['group'] & { baseColor?: string }) {
  const { nodes, materials } = useGLTF('/models/Triangle-transformed.glb') as GLTFResult
  
  // Clone materials so we can modify them without affecting other instances or the cache
  const baseMaterial = useMemo(() => {
    const m = materials.Base_Triangle.clone()
    m.color.set(baseColor)
    return m
  }, [materials.Base_Triangle, baseColor])

  const emissionMaterial = useMemo(() => {
    const m = materials.Emission_Triangle.clone()
    m.color.set(baseColor)
    m.emissive.set(baseColor)
    // Ensure it's bright enough to see
    m.emissiveIntensity = 5 
    return m
  }, [materials.Emission_Triangle, baseColor])

  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.006, 0]}>
        <mesh  geometry={nodes.Cube006.geometry} material={baseMaterial} />
        <mesh  geometry={nodes.Cube006_1.geometry} material={emissionMaterial} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Triangle-transformed.glb')
